trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 127.0.0.1:8881
    timeout: 1s
  grpc:
    addr: 127.0.0.1:8891
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:password@tcp(127.0.0.1:3306)/golang?parseTime=True
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
